language: ruby
cache: bundler
sudo: required
services:
  - rabbitmq
addons:
  apt:
    packages:
      - rabbitmq-server
rvm:
  - 2.6.5
  - 2.5.7
  - 2.4.9
  - 2.3.8
gemfile:
  - gemfiles/rails_60.gemfile
  - gemfiles/rails_52.gemfile
  - gemfiles/rails_51.gemfile
  - gemfiles/rails_50.gemfile
  - gemfiles/rails_42.gemfile

before_install:
  - echo yes | rvm gemset delete global
  - gem install bundler -v'~>1.0'
script:
  - bundle exec rake rubocop
  - bundle exec rake spec

matrix:
  exclude:
  - rvm: 2.4.9
    gemfile: gemfiles/rails_60.gemfile
  - rvm: 2.3.8
    gemfile: gemfiles/rails_60.gemfile
