language: ruby
cache: bundler
rvm:
  - '2.4.0'
  - '2.3.3'
  - '2.2.6'
before_install:
  - gem update --system
  - gem install bundler
script:
  - bundle exec rake rubocop
  - bundle exec rake spec
matrix:
  fast_finish: true
