language: ruby
cache: bundler
bundler_args: --without development
rvm:
  - '2.4.0'
  - '2.3.3'
  - '2.2.6'
  - '2.1.10'
before_script:
- export JRUBY_OPTS="--2.0"
before_install:
- gem update --system
- gem install bundler
matrix:
  fast_finish: true
