language: ruby
cache: bundler
sudo: required
services:
  - rabbitmq
addons:
  apt:
    packages:
      - rabbitmq-server
rvm:
  - 2.6.5
  - 2.5.7
  - 2.4.9
  - 2.3.8
env:
  - SPEC='--tag ~probe'
  - SPEC='--tag probe:faraday' FARADAY_VERSION='~> 0.9'
  - SPEC='--tag probe:faraday' FARADAY_VERSION='~> 1.0'
  - SPEC='--tag probe:msgr'
  - SPEC='--tag probe:rack'
  - SPEC='--tag probe:rails --tag ~probe' BUNDLE_GEMFILE=gemfiles/rails_42.gemfile
  - SPEC='--tag probe:rails --tag ~probe' BUNDLE_GEMFILE=gemfiles/rails_50.gemfile
  - SPEC='--tag probe:rails --tag ~probe' BUNDLE_GEMFILE=gemfiles/rails_51.gemfile
  - SPEC='--tag probe:rails --tag ~probe' BUNDLE_GEMFILE=gemfiles/rails_52.gemfile
  - SPEC='--tag probe:rails --tag ~probe' BUNDLE_GEMFILE=gemfiles/rails_60.gemfile
  - SPEC='--tag probe:restify'
  - SPEC='--tag probe:sidekiq' SIDEKIQ_VERSION='~> 5.0'
  - SPEC='--tag probe:sidekiq' SIDEKIQ_VERSION='~> 6.0'

before_install:
  - echo yes | rvm gemset delete global
  - gem install bundler --version '~> 1.0'
script:
  - bundle exec rspec ${SPEC}

matrix:
  exclude:
    - rvm: 2.4.9
      env: SPEC='--tag probe:rails --tag ~probe' BUNDLE_GEMFILE=gemfiles/rails_60.gemfile
    - rvm: 2.4.9
      env: SPEC='--tag probe:sidekiq' SIDEKIQ_VERSION='~> 6.0'
    - rvm: 2.3.8
      env: SPEC='--tag probe:rails --tag ~probe' BUNDLE_GEMFILE=gemfiles/rails_60.gemfile
    - rvm: 2.3.8
      env: SPEC='--tag probe:sidekiq' SIDEKIQ_VERSION='~> 6.0'
