name: Build
on:
  push:
    branches-ignore: [debian]

jobs:
  test:
    name: Ruby ${{ matrix.ruby }} / ${SUITE}
    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.6', '2.5', '2.4']
        suite:
          - core
          - faraday-0.9
          - faraday-1.0
          - msgr
          - rack
          - rails-4.2
          - rails-5.0
          - rails-5.1
          - rails-5.2
          - rails-6.0
          - restify
          - sidekiq-5
          - sidekiq-6
      include:
        - suite: core
          spec: --tag ~probe
        - suite: faraday-0.9
          spec: --tag probe:faraday
          faraday: ~> 0.9
        - suite: faraday-1.0
          spec: --tag probe:faraday
          faraday: ~> 1.0
        - suite: msgr
          spec: --tag probe:msgr
        - suite: rack
          spec: --tag probe:rack
        - suite: rails-4.2
          spec: --tag probe:rails --tag ~probe
          gemfile: gemfiles/rails_42.gemfile
        - suite: rails-5.0
          spec: --tag probe:rails --tag ~probe
          gemfile: gemfiles/rails_50.gemfile
        - suite: rails-5.1
          spec: --tag probe:rails --tag ~probe
          gemfile: gemfiles/rails_51.gemfile
        - suite: rails-5.2
          spec: --tag probe:rails --tag ~probe
          gemfile: gemfiles/rails_52.gemfile
        - suite: rails-6.0
          spec: --tag probe:rails --tag ~probe
          gemfile: gemfiles/rails_60.gemfile
        - suite: restify
          spec: --tag probe:restify
        - suite: sidekiq-5
          spec: --tag probe:sidekiq
          sidekiq: ~> 5.0
        - suite: sidekiq-6
          spec: --tag probe:sidekiq
          faraday: ~> 6.0

    env:
      SPEC: ${{ matrix.spec }}
      SUITE: ${{ matrix.suite }}
      FARADAY_VERSION: ${{ matrix.faraday }}
      SIDEKIQ_VERSION: ${{ matrix.sidekiq }}
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}

    services:
      rabbitmq:
        image: rabbitmq:latest
        ports: [5672/tcp]
        options: --health-cmd "rabbitmqctl node_health_check" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          architecture: 'x64'
      - uses: actions/cache@v1
        with:
          path: vendor
          key: v1-ruby-${{ matrix.ruby }}-suite-${{ matrix.suite }}

      - name: Install debian dependencies
        run: sudo apt-get install --yes --quiet libsqlite3-dev

      - name: Install Ruby dependencies
        run: |
          bundle config path "$(pwd)/vendor/bundle"
          bundle config without development
          bundle update --jobs=$(nproc) --retry=3

      - name: Run rspec
        env:
          REDMINE_VERSION: ${{ matrix.redmine }}
        run: bundle exec rspec --color
